### ISSUE TITLE
Tutorial example not working

### ISSUE THREAD

**Issue by Gabriel-p** [mcleonard/sampyl#22]
I'm testing `sampyl` in Python 2.7.15. I tried running the simple example shown here http://matatat.org/sampyl/, and I get:

```
Traceback (most recent call last):
  File "/home/gabriel/Dropbox/python-test/sampyl_test.py", line 13, in <module>
    nuts = smp.NUTS(logp, start)
  File "/home/gabriel/anaconda3/envs/asteca27/lib/python2.7/site-packages/sampyl/samplers/NUTS.py", line 77, in __init__
    super(NUTS, self).__init__(logp, start, **kwargs)
  File "/home/gabriel/anaconda3/envs/asteca27/lib/python2.7/site-packages/sampyl/samplers/base.py", line 32, in __init__
    start = {unicodedata.normalize('NFKC', key): val for key, val in start.items()}
  File "/home/gabriel/anaconda3/envs/asteca27/lib/python2.7/site-packages/sampyl/samplers/base.py", line 32, in <dictcomp>
    start = {unicodedata.normalize('NFKC', key): val for key, val in start.items()}
TypeError: normalize() argument 2 must be unicode, not str
```

Could this be related to the oldish version of Python I'm running?

**Comment by amppumas** [comment]
I have the same issue in python2, and changing to python3 fixed the issue it should work nontheless as python2 is supported.
